### PR TITLE
fix: Add more definitions to built .a

### LINKED ISSUE #2: Built libpq.a is missing many symbols
When building on a mac, with up-to-date Bazel, rules_rust, toolchains_llvm, the built libpq.a is missing many symbols. This shows up as errors linking a Rust binary that depends on :libpq. I confirmed with `nm -g` that those symbols needed at link-time were not present in the built .a file.

### PR DESCRIPTION
**Pull request by aran**
Add more C files as dependencies, along with several more defines, to define more symbols in the built result.

Tested by building and running a rust binary that uses diesel with this as the dependency, on a mac, with
 * no `--platforms`
 * a linux-x86_64 platform
 * a linux-arm64 platform

Fixes #2.

### CODE REVIEW

**Comment by dmeijboom** [comment]
@aran Sorry for the delay. We tested your changes on a couple of internal repositories and it seems to work just fine. Thanks!

**Review by dmeijboom — CHANGES_REQUESTED** [review]
The code LGTM but at brainhive all of the commits have to be signed. Can you do that? For more information: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by aran** [comment]
OK, fixed up that commit verification issue.

I also removed the MODULE.bazel.lock change, not sure if you wanted that included. If so, I figure you can decide that and commit it, since it's not strictly related to this.

With respect to the changes in this PR, it's been working for me without issue so far, but just want to be clear it is a bit concerning to me on several aspects:

1. I don't understand how you had things working without something like it, which makes me feel like I don't understand something about the overall build environment
2. I don't understand the implications of blanking out `getpeereid`, or why the postgres source doesn't work out of the box with the configured options 
3. It seems reasonable that `FRONTEND` is right but don't understand the implications of the `STRERROR` defines.

**Review by dmeijboom — APPROVED** [review]
LGTM

**Comment by dmeijboom** [comment]
> OK, fixed up that commit verification issue.
> 
> I also removed the MODULE.bazel.lock change, not sure if you wanted that included. If so, I figure you can decide that and commit it, since it's not strictly related to this.

Check! Let me know if it works for you on the `main` branch (without the `MODULE.bazel.lock` change). If not I'll add it anyways.

> 
> With respect to the changes in this PR, it's been working for me without issue so far, but just want to be clear it is a bit concerning to me on several aspects:
> 
>     1. I don't understand how you had things working without something like it, which makes me feel like I don't understand something about the overall build environment

I can say with confidence that I have a very poor understanding of how all of this works in the first place. It has been a matter of making changes, testing, verifying, etc. I still don't get why the original version worked (it might be due to some magic happening in `pq-sys` or with our toolchain not being fully hermetic). But it works and passes all of our tests so I guess it should be fine :-)

>     2. I don't understand the implications of blanking out `getpeereid`, or why the postgres source doesn't work out of the box with the configured options
>     3. It seems reasonable that `FRONTEND` is right but don't understand the implications of the `STRERROR` defines.

Me neither. If I have some time in the upcoming weeks I'll look further into this. I also wanted to add support for more architectures.

**Pull request merged**
